### ISSUE TITLE
accelereren_decelereren werkt niet

### ISSUE THREAD

**Issue by Sasha8888** [MetisMontessoriLyceum/baggerbusters-hydrodynamics#1]
Wanneer we accelereren_decelereren gebruiken wijkt de robot uit naar links, bij een normaal blokje doet hij dat niet dus het ligt vrij zeker aan het programma.

**Comment by hakkas** [comment]
Het probleem speelt nog steeds

**Comment by bokke1010** [comment]
Ga er zaterdag naar kijken, weet niet waarom het gebeurt maar heb wel een oplossing in gedachten

**Comment by bokke1010** [comment]
paar weken geleden gefixt, functie werd verkeerd gebruikt
